apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-app
  template:
    metadata:
      labels:
        app: devops-app
    spec:
      containers:
        - name: devops-container
          image: sedabayog/nodejs-devops-app:latest  # DockerHub'daki image'in adı
          ports:
            - containerPort: 3000
